logLevel: info

writeQueueSize: 1024
udpReadBufferSize: 4000000

# upstream feeds
rtmp: yes
rtmpAddress: 0.0.0.0:1935

# previews/debugs
hls: yes
hlsAddress: localhost:8888

# previews/debugs
webrtc: true
webrtcAddress: localhost:8889
webrtcLocalUDPAddress: 0.0.0.0:8189

# downstream feeds
srt: true
srtAddress: 0.0.0.0:8890

srtla: yes
srtlaAddress: 0.0.0.0:8891

# if needed, check all the needed ports with ufw
rtsp: no

metrics: yes
metricsAddress: localhost:9998

pathDefaults:
  # alwaysAvailable: true
  # alwaysAvailableFile: /etc/mediamtx/co-stream-proxy-no-signal.mp4
  runOnReady: >
    bash -c '
    while true; do
      mkdir -p $(dirname /var/mediamtx/snapshots/$MTX_PATH.jpg)
      ffmpeg -y -i http://localhost:8888/$MTX_PATH/index.m3u8 -frames:v 1 -update true /var/mediamtx/snapshots/$MTX_PATH.jpg 2>/dev/null
      sleep 5
    done'
  runOnReadyRestart: yes

paths:

  macos: {}
  x/macos: {}

  slot1: {}
  x/slot1: {}
  slot2: {}
  x/slot2: {}
  slot3: {}
  x/slot3: {}
  slot4: {}
  x/slot4: {}
  slot5: {}
  x/slot5: {}
  slot6: {}
  x/slot6: {}
  slot7: {}
  x/slot7: {}
  slot8: {}
  x/slot8: {}

  demo: {}
  x/demo: {}

  # restreaming to YouTube/Facebook (keys loaded from /etc/mediamtx/restream.env)
  restream:
    runOnReady: /etc/mediamtx/restream.sh
    runOnReadyRestart: yes

authInternalUsers:
{% for cred in credentials.stream_write %}
- user: "{{ cred.user }}"
  pass: "{{ cred.pass }}"
  permissions:
  - action: publish
  - action: read

{% endfor %}
{% for cred in credentials.stream_read %}
- user: "{{ cred.user }}"
  pass: "{{ cred.pass }}"
  permissions:
  - action: read

{% endfor %}
{% for cred in credentials.restream.write %}
- user: "{{ cred.user }}"
  pass: "{{ cred.pass }}"
  permissions:
  - action: publish
    path: restream
  - action: read
    path: restream

{% endfor %}
- user: any
  pass:
  ips: ['127.0.0.1', '::1']
  permissions:
  - action: api
  - action: metrics
  - action: pprof
  - action: publish
  - action: read
