# Path to local mediamtx source checkout (fork with SRTLA support)
stream_proxy__mediamtx_repo: "https://github.com/thejoeejoee/mediamtx.git"
stream_proxy__mediamtx_commit: "6bf29a9998971b70a05fd7c1347a881d11ce96fd"
