# Path to local mediamtx source checkout (fork with SRTLA support)
stream_proxy__mediamtx_repo: "https://github.com/thejoeejoee/mediamtx.git"
stream_proxy__mediamtx_commit: "66351dd7df86b25b6a404b2d21e6e5a9eb115053"
