csos:
  hosts:
    csos@orb:

  vars:
    ansible_user: csos

    credentials:
      stream_write:
        - { user: drone, pass: changeme }
        - { user: demo, pass: omed }
      stream_read:
        - { user: vmix, pass: changeme }
      telemetry:
        - { user: admin, pass: changeme }
      gfx:
        - { user: admin, pass: changeme }
      restream:
        youtube_key: ""
        facebook_key: ""
        write:
          - { user: restream, pass: changeme }

    web_proxy__domain: csos.orb.local
    web_proxy__disable_tls: true

    srtla__player_port: 4000
    srtla__sender_port: 4001
    srtla__stats_port: 8088
    srtla__mgnt_port: 3001
    srtla__srtla_port: 5000
    srtla__exporter_port: 7979
    srtla__slots:
      - { name: slot1, publish_key: changeme-slot1 }
      - { name: slot2, publish_key: changeme-slot2 }
      - { name: slot3, publish_key: changeme-slot3 }
      - { name: slot4, publish_key: changeme-slot4 }
      - { name: slot5, publish_key: changeme-slot5 }
      - { name: slot6, publish_key: changeme-slot6 }
      - { name: slot7, publish_key: changeme-slot7 }
      - { name: slot8, publish_key: changeme-slot8 }
