- name: Download mediamtx
  become: true
  unarchive:
    src: https://github.com/bluenviron/mediamtx/releases/download/v1.17.0/mediamtx_v1.17.0_linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Install mediamtx
  become: true
  copy:
    remote_src: yes
    src: /tmp/mediamtx
    dest: /usr/local/bin/mediamtx
    mode: '0755'

- name: UFW allow RTMP
  become: true
  ufw:
    rule: allow
    port: 1935
    proto: tcp

- name: UFW allow SRT
  become: true
  ufw:
    rule: allow
    port: 8890
    proto: udp

- name: UFW allow WebRTC UDP
  become: true
  ufw:
    rule: allow
    port: 8189
    proto: udp

- name: UFW allow WebRTC
  become: true
  ufw:
    rule: allow
    port: 8889
    proto: tcp

- name: Prepare mediamtx config directory
  become: true
  file:
    path: /etc/mediamtx
    state: directory

- name: Clean snapshot directory
  become: true
  file:
    path: /var/mediamtx/snapshots
    state: absent

- name: Prepare snapshot directory
  become: true
  file:
    path: /var/mediamtx/snapshots
    state: directory

- name: Prepare config
  become: true
  template:
    src: mediamtx.yml
    dest: /etc/mediamtx/mediamtx.yml
    mode: '0644'

- name: Prepare offline segment video
  become: true
  copy:
    src: ../resources/co-stream-proxy-no-signal.mp4
    dest: /etc/mediamtx/co-stream-proxy-no-signal.mp4
    mode: '0644'

- name: Mediamtx systemd service is prepared
  become: true
  template:
    src: mediamtx.service
    dest: /usr/lib/systemd/system/csos-mediamtx.service

- name: Mediamtx systemd service is reloaded
  become: true
  systemd:
    daemon_reload: true

- name: Mediamtx systemd service is enabled
  become: true
  systemd:
    name: csos-mediamtx.service
    enabled: true
    state: started
