- name: Restart auth stack
  community.docker.docker_compose_v2:
    project_src: /opt/auth/
    files:
      - docker-compose.yml
    state: restarted

- name: Restart oauth2-proxy
  community.docker.docker_container:
    name: auth-oauth2-proxy-1
    state: started
    restart: true
  become: true
