- name: UFW allow 80
  become: true
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW allow 443
  become: true
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Install Caddy
  block:
    - include_role:
        name: caddy_ansible.caddy_ansible
      vars:
        caddy_conf_filename: Caddyfile
        caddy_config: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
        caddy_config_update: false

        caddy_systemd_restart_startlimitinterval: 60
  become: true

- name: Deploy Caddyfile
  become: true
  ansible.builtin.copy:
    content: "{{ lookup('template', 'templates/Caddyfile.j2') }}"
    dest: /etc/caddy/Caddyfile
    owner: www-data
    mode: "0640"
    validate: "caddy validate --config %s --adapter caddyfile"
  notify: Restart caddy
